use capability_protocol::{
    ApiVersion, AuthorityRef, Capability, CapabilityCatalog, CapabilityMetadata, CapabilityPolicy,
    CapabilitySpec, CatalogKind, ErrorCode, ErrorReport, ErrorReportKind, LoadMode, LoadSpec,
    ObservedCapability, ObservedCatalog, ObservedKind, Permission, PolicyKind, PolicyMetadata,
    PolicyRef, PolicySpec, ProtocolDocumentKind, ReconcileAction, ReconcilePlan, ReconcilePlanKind,
    ResourceLimits, RouteDecision, RouteMatch, RouteResult, RouteResultKind, SelectorRef,
    ValidationReport, ValidationReportKind,
};
use schemars::schema_for;
use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use ts_rs::{Config, TS};

const HEADER: &str = "// @generated by `cargo run -p xtask -- codegen`; do not edit.\n";

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = std::env::args().skip(1);
    let command = args.next();
    let check = match (command.as_deref(), args.next().as_deref(), args.next()) {
        (Some("codegen"), None, None) => false,
        (Some("codegen"), Some("--check"), None) => true,
        _ => return Err("usage: cargo run -p xtask -- codegen [--check]".into()),
    };

    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .ok_or("xtask must remain under crates/xtask")?;
    let artifacts = artifacts()?;
    if check {
        verify(repo_root, &artifacts)?;
        println!("generated protocol artifacts are current");
    } else {
        write(repo_root, &artifacts)?;
        println!("generated {} protocol artifacts", artifacts.len());
    }
    Ok(())
}

fn artifacts() -> Result<BTreeMap<PathBuf, String>, Box<dyn Error>> {
    let mut files = BTreeMap::new();
    for kind in ProtocolDocumentKind::ALL.iter().copied() {
        files.insert(PathBuf::from(kind.schema_path()), schema(kind)?);
    }
    files.insert(
        PathBuf::from("generated/clients/typescript/capability-protocol.ts"),
        typescript(),
    );
    files.insert(
        PathBuf::from("generated/README.md"),
        format!(
            "{HEADER}\n# Generated Contracts\n\nRust types in `crates/capability-protocol` are the only semantic source.\nRun `cargo run -p xtask -- codegen --check` to detect drift.\n"
        ),
    );
    Ok(files)
}

fn schema(kind: ProtocolDocumentKind) -> Result<String, serde_json::Error> {
    match kind {
        ProtocolDocumentKind::Catalog => pretty(&schema_for!(CapabilityCatalog)),
        ProtocolDocumentKind::Policy => pretty(&schema_for!(CapabilityPolicy)),
        ProtocolDocumentKind::Observed => pretty(&schema_for!(ObservedCatalog)),
        ProtocolDocumentKind::Route => pretty(&schema_for!(RouteResult)),
        ProtocolDocumentKind::Reconcile => pretty(&schema_for!(ReconcilePlan)),
        ProtocolDocumentKind::Validation => pretty(&schema_for!(ValidationReport)),
        ProtocolDocumentKind::Error => pretty(&schema_for!(ErrorReport)),
    }
}

fn pretty<T: serde::Serialize>(value: &T) -> Result<String, serde_json::Error> {
    serde_json::to_string_pretty(value).map(|mut value| {
        value.push('\n');
        value
    })
}

fn typescript() -> String {
    let config = Config::default();
    let mut declarations = vec![
        export_decl::<ApiVersion>(&config),
        export_decl::<CatalogKind>(&config),
        export_decl::<PolicyKind>(&config),
        export_decl::<ObservedKind>(&config),
        export_decl::<RouteResultKind>(&config),
        export_decl::<ReconcilePlanKind>(&config),
        export_decl::<ValidationReportKind>(&config),
        export_decl::<ErrorReportKind>(&config),
        export_decl::<Capability>(&config),
        export_decl::<CapabilityMetadata>(&config),
        export_decl::<CapabilitySpec>(&config),
        export_decl::<AuthorityRef>(&config),
        export_decl::<LoadSpec>(&config),
        export_decl::<LoadMode>(&config),
        export_decl::<Permission>(&config),
        export_decl::<PolicyMetadata>(&config),
        export_decl::<PolicySpec>(&config),
        export_decl::<ResourceLimits>(&config),
        export_decl::<ObservedCapability>(&config),
        export_decl::<ErrorCode>(&config),
        export_decl::<PolicyRef>(&config),
        export_decl::<SelectorRef>(&config),
        export_decl::<RouteDecision>(&config),
        export_decl::<RouteMatch>(&config),
        export_decl::<ReconcileAction>(&config),
    ];
    declarations.extend(
        ProtocolDocumentKind::ALL
            .iter()
            .copied()
            .map(|kind| kind.typescript_root_declaration(&config)),
    );
    format!("{HEADER}\n{}\n", declarations.join("\n\n"))
}

fn export_decl<T: TS>(config: &Config) -> String {
    let mut output = T::docs().unwrap_or_default();
    output.push_str("export ");
    output.push_str(&T::decl(config));
    output
}

fn verify(repo_root: &Path, artifacts: &BTreeMap<PathBuf, String>) -> Result<(), Box<dyn Error>> {
    let expected = artifacts.keys().cloned().collect::<BTreeSet<_>>();
    let actual = generated_files(repo_root)?;
    if actual != expected {
        return Err(
            format!("generated file set drift: expected {expected:?}, found {actual:?}").into(),
        );
    }
    for (relative, expected_content) in artifacts {
        let actual_content = fs::read_to_string(repo_root.join(relative))?;
        if actual_content != *expected_content {
            return Err(format!("generated artifact drift: {}", relative.display()).into());
        }
    }
    Ok(())
}

fn write(repo_root: &Path, artifacts: &BTreeMap<PathBuf, String>) -> Result<(), Box<dyn Error>> {
    for (relative, content) in artifacts {
        let destination = repo_root.join(relative);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(destination, content)?;
    }
    Ok(())
}

fn generated_files(repo_root: &Path) -> Result<BTreeSet<PathBuf>, Box<dyn Error>> {
    let generated_root = repo_root.join("generated");
    if !generated_root.exists() {
        return Ok(BTreeSet::new());
    }
    let mut found = BTreeSet::new();
    collect_files(repo_root, &generated_root, &mut found)?;
    Ok(found)
}

fn collect_files(
    repo_root: &Path,
    directory: &Path,
    found: &mut BTreeSet<PathBuf>,
) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_files(repo_root, &path, found)?;
        } else if path.is_file() {
            found.insert(path.strip_prefix(repo_root)?.to_path_buf());
        }
    }
    Ok(())
}
